markets = [
    "CS.D.AUDUSD.MINI.IP",
    "CS.D.GBPUSD.MINI.IP",
    "CS.D.EURUSD.MINI.IP"
    # "CS.D.USDJPY.MINI.IP",
    # "CS.D.EURJPY.MINI.IP",
    # "CS.D.USDCAD.MINI.IP",
    # "CS.D.EURGBP.MINI.IP",
    # "CS.D.USDCHF.MINI.IP",
    # "CS.D.EURCHF.MINI.IP",
    # "CS.D.GBPEUR.MINI.IP",
    # "CS.D.GBPJPY.MINI.IP",
    # "CS.D.EURCAD.MINI.IP",
    # "CS.D.GBPCAD.MINI.IP",
    # "CS.D.GBPCHF.MINI.IP",
    # "CS.D.CADJPY.MINI.IP",
    # "CS.D.CHFJPY.MINI.IP",
    # "CS.D.EURSDG.MINI.IP",
    # "CS.D.USDSDG.MINI.IP",
    # "CS.D.CADCHF.MINI.IP",
    # "CS.D.USDZAR.MINI.IP",
    # "CS.D.GBPZAR.MINI.IP",
    # "CS.D.SDGJPY.MINI.IP",
    # "CS.D.USDZAR.MINI.IP",
    # "CS.D.EURZAR.MINI.IP"
]