ACCOUNT = 'https://demo-api.ig.com/gateway/deal/session/'
WATCHLIST = 'https://demo-api.ig.com/gateway/deal/positions/'
ORDER  = 'https://demo-api.ig.com/gateway/deal/workingorders/'
POSITION  = 'https://demo-api.ig.com/gateway/deal/positions/'
MARKET = 'https://demo-api.ig.com/gateway/deal/markets/'
PRICE = 'https://demo-api.ig.com/gateway/deal/prices/'